version: '3.2'

services:

  app:
    image: bamarni/php:7-cli
    volumes:
      - ./:/app
    working_dir: /app
    command: php ./bin/console server:run 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always

  prometheus:
    image: prom/prometheus:v1.8.2
    depends_on:
      - app
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - ./var/prometheus:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:4.6.1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./var/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
