parameters:
#    eni_demo.example.class: Eni\DemoBundle\Example

services:
#    eni_demo.example:
#        class: %eni_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
